 export enum Action {
    LOGIN = 'LOGIN',

    CREATE_RECIPE = 'CREATE_RECIPE',
    UPDATE_RECIPE = 'UPDATE_RECIPE',
    DELETE_RECIPE = 'DELETE_RECIPE',

    CREATE_INGREDIENT = 'CREATE_INGREDIENT',
    UPDATE_INGREDIENT = 'UPDATE_INGREDIENT',
    DELETE_INGREDIENT = 'DELETE_INGREDIENT',

    BUY_INGREDIENT = 'BUY_INGREDIENT',
    COMPLETE_SHOPPING_LIST = 'COMPLETE_SHOPPING_LIST',

    CREATE_COMMENT = 'CREATE_COMMENT',
    UPDATE_COMMENT = 'UPDATE_COMMENT',
    RESOLVE_COMMENT = 'RESOLVE_COMMENT',
    DELETE_COMMENT = 'DELETE_COMMENT',

    OPEN_TUTORIAL = 'OPEN_TUTORIAL',

    SUBMIT_FEEDBACK = 'SUBMIT_FEEDBACK',
}

export enum ActionLabel {
    LOGIN = 'Login',

    CREATE_RECIPE = 'Create Recipe',
    UPDATE_RECIPE = 'Update Recipe',
    DELETE_RECIPE = 'Delete Recipe',

    CREATE_INGREDIENT = 'Create Ingredient',
    UPDATE_INGREDIENT = 'Update Ingredient',
    DELETE_INGREDIENT = 'Delete Ingredient',

    BUY_INGREDIENT = 'Buy Ingredient',
    COMPLETE_SHOPPING_LIST = 'Complete Shopping List',

    CREATE_COMMENT = 'Create Comment',
    UPDATE_COMMENT = 'Update Comment',
    RESOLVE_COMMENT = 'Resolve Comment',
    DELETE_COMMENT = 'Delete Comment',

    SUBMIT_FEEDBACK = 'Submit Feedback',
}
