export enum Action {
    LOGIN = 'LOGIN',

    CREATE_RECIPE = 'CREATE_RECIPE',
    DELETE_RECIPE = 'DELETE_RECIPE',

    CREATE_INGREDIENT = 'CREATE_INGREDIENT',
    DELETE_INGREDIENT = 'DELETE_INGREDIENT',
}
