 export enum Action {
    LOGIN = 'LOGIN',

    CREATE_RECIPE = 'CREATE_RECIPE',
    UPDATE_RECIPE = 'UPDATE_RECIPE',
    DELETE_RECIPE = 'DELETE_RECIPE',

    CREATE_INGREDIENT = 'CREATE_INGREDIENT',
    UPDATE_INGREDIENT = 'UPDATE_INGREDIENT',
    DELETE_INGREDIENT = 'DELETE_INGREDIENT',

    BUY_INGREDIENT = 'BUY_INGREDIENT',
}
