 export enum Action {
    LOGIN = 'LOGIN',

    CREATE_RECIPE = 'CREATE_RECIPE',
    UPDATE_RECIPE = 'UPDATE_RECIPE',
    DELETE_RECIPE = 'DELETE_RECIPE',

    CREATE_INGREDIENT = 'CREATE_INGREDIENT',
    UPDATE_INGREDIENT = 'UPDATE_INGREDIENT',
    DELETE_INGREDIENT = 'DELETE_INGREDIENT',

    CREATE_ITEM = 'CREATE_ITEM',
    UPDATE_ITEM = 'UPDATE_ITEM',
    DELETE_ITEM = 'DELETE_ITEM',

    BUY_INGREDIENT = 'BUY_INGREDIENT',
    COMPLETE_SHOPPING_LIST = 'COMPLETE_SHOPPING_LIST',
}
